### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'use_qlora'

### ISSUE THREAD

**Issue by freelancerllm** [THUDM/VisualGLM-6B#109]
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
/root/miniconda3/lib/python3.8/site-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
Traceback (most recent call last):
  File "cli_demo.py", line 103, in <module>
    main()
  File "cli_demo.py", line 30, in main
    model, model_args = AutoModel.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/sat/model/base_model.py", line 282, in from_pretrained
    model = get_model(args, model_cls, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/sat/model/base_model.py", line 305, in get_model
    model = model_cls(args, params_dtype=params_dtype, **kwargs)
  File "/mnt/niujie.nj/VisualGLM-6B/finetune_visualglm.py", line 20, in __init__
    elif args.use_qlora:
AttributeError: 'Namespace' object has no attribute 'use_qlora'

**Comment by 1049451037** [comment]
Please use the latest github code.
