### ISSUE TITLE
运行cli_demo_hf 推理出现问题：NameError: name 'round_up' is not defined

### ISSUE THREAD

**Issue by SixGoodX** [THUDM/VisualGLM-6B#158]
Failed to load cpm_kernels:libnvrtc.so.11.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/code_all/ChatGLM-6B/visualglm/demo.py", line 8, in <module>
    model = AutoModel.from_pretrained(model_path, trust_remote_code=True).quantize(4).half().cuda()
  File "/home/.cache/huggingface/modules/transformers_modules/visualglm-6b/modeling_chatglm.py", line 1337, in quantize
    self.transformer = quantize(self.transformer, bits, empty_init=empty_init, **kwargs)
  File "/home/.cache/huggingface/modules/transformers_modules/visualglm-6b/quantization.py", line 157, in quantize
    layer.attention.query_key_value = QuantizedLinear(
  File "/home/.cache/huggingface/modules/transformers_modules/visualglm-6b/quantization.py", line 137, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "/home/.cache/huggingface/modules/transformers_modules/visualglm-6b/quantization.py", line 76, in compress_int4_weight
    blockDim = (min(round_up(m, 32), 1024), 1, 1)
NameError: name 'round_up' is not defined

很奇怪，半个月前，还能运行？

**Comment by SixGoodX** [comment]
## 是4位量化后的模型
from transformers import AutoTokenizer, AutoModel

model_path = "/home/liuhao/code_all/ChatGLM-6B/visualglm/model/visualglm-6b"
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).quantize(4).half().cuda()

image_path = "user_1.png"
response, history = model.chat(tokenizer, image_path, "描述这张图片。", history=[])
print(response)

**Comment by SixGoodX** [comment]
是4位量化后的模型
from transformers import AutoTokenizer, AutoModel

model_path = "./model/visualglm-6b"
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).quantize(4).half().cuda()

image_path = "user_1.png"
response, history = model.chat(tokenizer, image_path, "描述这张图片。", history=[])
print(response)

**Comment by BUZZ0328** [comment]
> 已解决

请问怎么解决的，我是用cli_demo.py也出现了同样的问题
