### ISSUE TITLE
finetune.sh running error

### ISSUE THREAD

**Issue by youngstu** [THUDM/VisualGLM-6B#165]
FAILED: multi_tensor_adam.cuda.o 
/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/includes -I/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/adam -isystem /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include -isystem /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/TH -isystem /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/THC -isystem /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/include -isystem /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -DBF16_AVAILABLE -std=c++14 -c /home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
In file included from /home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:11:0:
/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++14 or later compatible compiler is required to use ATen.
 #error C++14 or later compatible compiler is required to use ATen.
  ^
In file included from /usr/include/c++/4.8.2/mutex:35:0,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/core/Generator.h:4,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/Context.h:3,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:11:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/util/Exception.h:4:0,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/Context.h:3,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:11:
/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/macros/Macros.h:138:20: error: missing binary operator before token "("
 #if __has_attribute(used)
                    ^
/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/macros/Macros.h:218:22: error: missing binary operator before token "("
 #elif __has_attribute(always_inline) || defined(__GNUC__)
                      ^
In file included from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/util/string_view.h:4:0,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/util/StringUtil.h:6,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/util/Exception.h:6,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/Context.h:3,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:11:
/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/util/C++17.h:16:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
 #error \
  ^
/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++14 to compile PyTorch
 #error You need C++14 to compile PyTorch
  ^
In file included from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/util/typeid.h:25:0,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/core/ScalarTypeToTypeMeta.h:5,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/core/TensorOptions.h:10,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/core/TensorImpl.h:10,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/core/GeneratorImpl.h:12,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/core/Generator.h:22,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/Context.h:3,
                 from /home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:11:
/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/c10/util/TypeIndex.h:76:2: error: #error "You're running a too old version of GCC. We need GCC 5 or later."
 #error "You're running a too old version of GCC. We need GCC 5 or later."
  ^
In file included from /home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:13:0:
/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:10:24: fatal error: cusolverDn.h: No such file or directory
 #include <cusolverDn.h>
                        ^
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yangshaoxiong/shaoxiong/LLM_work/MLLM_work/research/VisualGLM-6B-debug/finetune_visualglm.py", line 200, in <module>
    training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=create_dataset_function, collate_fn=data_collator)
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/sat/training/deepspeed_training.py", line 98, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/sat/training/deepspeed_training.py", line 161, in setup_model_untrainable_params_and_optimizer
    model, optimizer, _, _ = deepspeed.initialize(
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1235, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 454, in load
    return self.jit_load(verbose)
  File "/home/yangshaoxiong/.local/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 497, in jit_load
    op_module = load(name=self.name,
  File "/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'
yq01-inf-hic-k8s-a100-aa24-530:16022:25129 [0] NCCL INFO [Service thread] Connection closed by localRank 0
yq01-inf-hic-k8s-a100-aa24-530:16022:16022 [0] NCCL INFO comm 0x55bae0db1390 rank 0 nranks 1 cudaDev 0 busId 65000 - Abort COMPLETE
yq01-inf-hic-k8s-a100-aa24-530:16022:25133 [0] NCCL INFO [Service thread] Connection closed by localRank 0
yq01-inf-hic-k8s-a100-aa24-530:16022:16022 [0] NCCL INFO comm 0x55bade01e040 rank 0 nranks 1 cudaDev 0 busId 65000 - Abort COMPLETE
[2023-07-06 17:07:05,316] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 16022
[2023-07-06 17:07:05,316] [ERROR] [launch.py:321:sigkill_handler] ['/home/yangshaoxiong/.conda/envs/py39_pytorch1.13/bin/python3.9', '-u', 'finetune_visualglm.py', '--local_rank=0', '--experiment-name', 'finetune-visualglm-6b', '--model-parallel-size', '1', '--mode', 'finetune', '--train-iters', '300', '--resume-dataloader', '--max_source_length', '64', '--max_target_length', '256', '--lora_rank', '10', '--layer_range', '0', '14', '--pre_seq_len', '4', '--train-data', './fewshot-data/dataset.json', '--valid-data', './fewshot-data/dataset.json', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--save-interval', '300', '--eval-interval', '10000', '--save', './checkpoints', '--split', '1', '--eval-iters', '10', '--eval-batch-size', '8', '--zero-stage', '1', '--lr', '0.0001', '--batch-size', '4', '--skip-init', '--fp16', '--use_lora'] exits with return code = 1

**Comment by 1049451037** [comment]
试一下`apt-get update`然后`apt-get install ninja-build`呢

**Comment by youngstu** [comment]
site-packages/torch/include/c10/util/C++17.h:16:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."

是不是GCC版本低的问题呢，我现在用的是conda 虚拟环境，替换gcc到10后，直接coredump

**Comment by elesun2018** [comment]
请问微调VisualGLM-6B# bash finetune/finetune_visualglm.sh，出现问题torch/utils/cpp_extension.py
raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'是什么原因
