### ISSUE TITLE
加载微调后模型再次微调

### ISSUE THREAD

**Issue by zgjiangtoby** [THUDM/VisualGLM-6B#169]
第一轮微调后，想继续第二轮微调，请问可以直接用finetune_visualglm.py加载微调后的checkpoints吗？

**Comment by 1049451037** [comment]
可以，把这行的model_type改成你的checkpoint路径即可：https://github.com/THUDM/VisualGLM-6B/blob/main/finetune_visualglm.py#L178

**Comment by zgjiangtoby** [comment]
> 可以，把这行的model_type改成你的checkpoint路径即可：https://github.com/THUDM/VisualGLM-6B/blob/main/finetune_visualglm.py#L178

我将路径修改后，报如下错误：

`[2023-07-11 15:45:33,573] [INFO] [RANK 0] global rank 0 is loading checkpoint ./checkpoints/finetune-visualglm-6b-07-04-12-32/9429
/mp_rank_00_model_states.pt
Traceback (most recent call last):
  File "/home/yejiang/atlas_shoulders/VisualGLM-6B/finetune_visualglm.py", line 199, in <module>
    model, args = FineTuneVisualGLMModel.from_pretrained(model_type, args)
  File "/home/yejiang/anaconda3/envs/atlas/lib/python3.10/site-packages/sat/model/base_model.py", line 216, in from_pretrained
    load_checkpoint(model, args, load_path=model_path, prefix=prefix)  
  File "/home/yejiang/anaconda3/envs/atlas/lib/python3.10/site-packages/sat/training/model_io.py", line 208, in load_checkpoint
    missing_keys, unexpected_keys = module.load_state_dict(sd['module'], strict=False)
  File "/home/yejiang/anaconda3/envs/atlas/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2027, in load_state_dict
    load(self, state_dict)
  File "/home/yejiang/anaconda3/envs/atlas/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "/home/yejiang/anaconda3/envs/atlas/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  File "/home/yejiang/anaconda3/envs/atlas/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2015, in load
    load(child, child_state_dict, child_prefix)
  [Previous line repeated 3 more times]
  File "/home/yejiang/anaconda3/envs/atlas/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2009, in load
    module._load_from_state_dict(
  File "/home/yejiang/atlas_shoulders/VisualGLM-6B/lora_mixin.py", line 47, in _load_from_state_dict
    self.weight.data.copy_(state_dict[prefix+'weight'])
RuntimeError: The size of tensor a (12288) must match the size of tensor b (25165824) at non-singleton dimension 0`

请问您知道大概原因吗？

**Comment by 1049451037** [comment]
哦，因为你是用qlora微调的。那就再把176行、180行、181行注释掉，再跑一下试试呢

* https://github.com/THUDM/VisualGLM-6B/blob/main/finetune_visualglm.py#L176
* https://github.com/THUDM/VisualGLM-6B/blob/main/finetune_visualglm.py#L180
