### ISSUE TITLE
使用HF的模型拿到的结果很离谱，和HF space中拿到的也不一致。

### ISSUE THREAD

**Issue by Chen94yue** [THUDM/VisualGLM-6B#189]
如题

**Comment by 1049451037** [comment]
请给出一些更详细的信息，比如拿到的结果是什么样的

**Comment by Chen94yue** [comment]
<img width="1606" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/34304578/95d448af-21cd-44bc-89f4-422c2e747fb6">
这是在hf的space中的结果。
<img width="1577" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/34304578/ac779a27-1608-4fbf-8fdf-a9f46a14e4ed">
这是本地运行的结果

**Comment by 1049451037** [comment]
看起来是本地的结果没有传给模型图片信息，请确保输入给模型的有image信息

**Comment by Chen94yue** [comment]
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/visualglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/visualglm-6b", trust_remote_code=True).half().cuda()
image_path = "/home/jd/Project/Vision/pil_003.jpg"
response, history = model.chat(tokenizer, image_path, "图像里面是什么东西?", history=[])
print(response)

这是我测试的代码，有什么问题吗？

**Comment by 1049451037** [comment]
huggingface的代码不是我维护的，cc @duzx16

**Comment by Chen94yue** [comment]
另外一个的模型文件可以单独下载吗？自动下载一直断

**Comment by 1049451037** [comment]
可以使用sat版本的模型，网络比huggingface要稳定很多，下载速度也快很多

**Comment by Chen94yue** [comment]
我下载sat的一直断，有单独的下载链接吗？

**Comment by 1049451037** [comment]
sat的总共就一个zip文件

**Comment by Chen94yue** [comment]
Traceback (most recent call last):
  File "/home/jd/Project/Vision/VisualGLM-6B/inference.py", line 5, in <module>
    model, model_args = VisualGLMModel.from_pretrained('visualglm-6b', args=argparse.Namespace(fp16=True, skip_init=True))
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/sat/model/base_model.py", line 201, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/sat/resources/download.py", line 68, in auto_create
    raise e
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/sat/resources/download.py", line 62, in auto_create
    download_s3(path, url[5:])
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/sat/resources/download.py", line 107, in download_s3
    bucket.download_file(remote_uri, os.path.join(local_dir, os.path.basename(remote_uri)),Callback=ProgressPercentage(client, SAT_BUCKET, remote_uri), Config=transfer_config)
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/boto3/s3/inject.py", line 277, in bucket_download_file
    return self.meta.client.download_file(
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/boto3/s3/inject.py", line 190, in download_file
    return transfer.download_file(
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/boto3/s3/transfer.py", line 326, in download_file
    future.result()
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/s3transfer/download.py", line 583, in _main
    for chunk in chunks:
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/s3transfer/download.py", line 728, in __next__
    chunk = self._body.read(self._chunksize)
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/s3transfer/utils.py", line 599, in read
    value = self._stream.read(*args, **kwargs)
  File "/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/botocore/response.py", line 104, in read
    raise ResponseStreamingError(error=e)
botocore.exceptions.ResponseStreamingError: An error occurred while reading from response stream: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

我的下载一直断，可以提供完整的链接吗？

**Comment by 1049451037** [comment]
cloundflare对于大于1GB的文件没有下载链接，只能使用他们的api下载，只能看一下你本地网络能否解决一下了。

**Comment by Chen94yue** [comment]
我这边用sat的模型也进行了测试，结果还是不对。
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
[2023-07-20 17:36:07,641] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-20 17:36:08,098] [INFO] building VisualGLMModel model ...
[2023-07-20 17:36:08,108] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-07-20 17:36:08,109] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
[2023-07-20 17:36:13,328] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 7802193408
[2023-07-20 17:36:16,066] [INFO] [RANK 0] global rank 0 is loading checkpoint /home/jd/.sat_models/visualglm-6b/1/mp_rank_00_model_states.pt
[2023-07-20 17:36:24,364] [INFO] [RANK 0] Will continue but found unexpected_keys! Check whether you are loading correct checkpoints: ['transformer.position_embeddings.weight'].
[2023-07-20 17:36:24,374] [INFO] [RANK 0] > successfully loaded /home/jd/.sat_models/visualglm-6b/1/mp_rank_00_model_states.pt
This is a scene of a group of people in a small house with the front door open, seen from above. The top floor has several cars and houses visible on it. There are some trees nearby that can be seen from here, as well as a few vehicles on the street.
根据图片描述，这张图片可能是在一个小公寓或别墅中的某个房间或者花园里拍摄的。这个场景展现了一个住宅建筑的一部分，包括房屋的外观、屋顶上的树以及周围的环境。
测试图像是这个：
![pil_003](https://github.com/THUDM/VisualGLM-6B/assets/34304578/f4392a69-25fa-487b-bdab-47029bf78d36)
测试代码是这个：
import argparse
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
from model import chat, VisualGLMModel
model, model_args = VisualGLMModel.from_pretrained('visualglm-6b', args=argparse.Namespace(fp16=True, skip_init=True))
from sat.model.mixins import CachedAutoregressiveMixin
model.add_mixin('auto-regressive', CachedAutoregressiveMixin())
image_path = "/home/jd/Project/Vision/pil_003.jpg"
response, history, cache_image = chat(image_path, model, tokenizer, "描述这张图片。", history=[])
print(response)
response, history, cache_image = chat(None, model, tokenizer, "这张图片可能是在什么场所拍摄的？", history=history, image=cache_image)
print(response)

**Comment by 1049451037** [comment]
直接运行cli_demo.py试一下呢

**Comment by Chen94yue** [comment]
[2023-07-20 17:44:15,280] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-20 17:44:15,925] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-07-20 17:44:15,926] [INFO] building VisualGLMModel model ...
[2023-07-20 17:44:15,936] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-07-20 17:44:15,937] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
/home/jd/miniconda3/envs/FastSAM/lib/python3.9/site-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
[2023-07-20 17:44:21,802] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 7802193408
[2023-07-20 17:44:22,636] [INFO] [RANK 0] global rank 0 is loading checkpoint /home/jd/.sat_models/visualglm-6b/1/mp_rank_00_model_states.pt
[2023-07-20 17:44:29,909] [INFO] [RANK 0] Will continue but found unexpected_keys! Check whether you are loading correct checkpoints: ['transformer.position_embeddings.weight'].
[2023-07-20 17:44:29,910] [INFO] [RANK 0] > successfully loaded /home/jd/.sat_models/visualglm-6b/1/mp_rank_00_model_states.pt
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
欢迎使用 VisualGLM-6B 模型，输入图像URL或本地路径读图，继续输入内容对话，clear 重新开始，stop 终止程序
请输入图像路径或URL（回车进入纯文本对话）： /home/jd/Project/Vision/pil_003.jpg
VisualGLM-6B：这张图片描绘了一个场景，一位女性正在吃晚餐。她穿着白色衬衫和黑色裤子，戴着一顶帽子。桌子周围有一束花和一个咖啡杯，桌子上放着一些食物。整个画面充满了温馨的氛围，让人感受到一种平静、舒适的感觉。
结果是相似的，也差的很多。

**Comment by 1049451037** [comment]
呃，这不对吧，是不是你加载的checkpoint不是直接从r2链接下载的

**Comment by Chen94yue** [comment]
Package                       Version
----------------------------- -----------
actionlib                     1.14.0
aiofiles                      23.1.0
aiohttp                       3.8.4
aiosignal                     1.3.1
altair                        5.0.1
angles                        1.9.13
annotated-types               0.5.0
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
asttokens                     2.2.1
async-timeout                 4.0.2
attrs                         23.1.0
backcall                      0.2.0
bleach                        6.0.0
blinker                       1.6.2
blis                          0.7.9
bondpy                        1.8.6
boto3                         1.28.6
botocore                      1.31.6
braceexpand                   0.1.7
cachetools                    5.3.1
camera-calibration            1.17.0
camera-calibration-parsers    1.12.0
catalogue                     2.0.8
catkin                        0.8.10
certifi                       2023.5.7
cfgv                          3.3.1
charset-normalizer            3.2.0
click                         8.1.4
clip                          1.0
cmake                         3.26.4
confection                    0.1.0
contexttimer                  0.3.3
contourpy                     1.1.0
controller-manager            0.19.6
controller-manager-msgs       0.19.6
cpm-kernels                   1.0.11
cv-bridge                     1.16.2
cycler                        0.11.0
cymem                         2.0.7
datasets                      2.13.1
decorator                     5.1.1
decord                        0.6.0
deepspeed                     0.10.0
diagnostic-analysis           1.11.0
diagnostic-common-diagnostics 1.11.0
diagnostic-updater            1.11.0
dill                          0.3.6
distlib                       0.3.6
dynamic-reconfigure           1.7.3
einops                        0.6.1
exceptiongroup                1.1.2
executing                     1.2.0
fairscale                     0.4.4
fastapi                       0.100.0
ffmpy                         0.3.0
filelock                      3.12.2
fonttools                     4.41.0
frozenlist                    1.4.0
fsspec                        2023.6.0
ftfy                          6.1.1
gazebo_plugins                2.9.2
gazebo_ros                    2.9.2
gencpp                        0.7.0
geneus                        3.0.0
genlisp                       0.4.18
genmsg                        0.6.0
gennodejs                     2.0.2
genpy                         0.6.15
gitdb                         4.0.10
GitPython                     3.1.32
gradio                        3.35.2
gradio_client                 0.2.9
h11                           0.14.0
hjson                         3.1.0
httpcore                      0.17.3
httpx                         0.24.1
huggingface-hub               0.16.4
identify                      2.5.24
idna                          3.4
image-geometry                1.16.2
imageio                       2.31.1
importlib-metadata            6.8.0
importlib-resources           6.0.0
interactive-markers           1.12.0
iopath                        0.1.10
ipython                       8.14.0
jedi                          0.18.2
Jinja2                        3.1.2
jmespath                      1.0.1
joint-state-publisher         1.15.1
joint-state-publisher-gui     1.15.1
jsonschema                    4.18.2
jsonschema-specifications     2023.6.1
kaggle                        1.5.15
kiwisolver                    1.4.4
langcodes                     3.3.0
laser_geometry                1.6.7
latex2mathml                  3.76.0
lazy_loader                   0.3
linkify-it-py                 2.0.2
lit                           16.0.6
Markdown                      3.4.3
markdown-it-py                2.2.0
MarkupSafe                    2.1.3
matplotlib                    3.7.2
matplotlib-inline             0.1.6
mdit-py-plugins               0.3.3
mdtex2html                    1.2.0
mdurl                         0.1.2
message-filters               1.16.0
moveit-commander              1.1.11
moveit-core                   1.1.11
moveit-python                 0.4.5
moveit-ros-planning-interface 1.1.11
moveit-ros-visualization      1.1.11
moveit-task-constructor-core  0.1.3
mpmath                        1.3.0
multidict                     6.0.4
multiprocess                  0.70.14
murmurhash                    1.0.9
networkx                      3.1
ninja                         1.11.1
nodeenv                       1.8.0
numpy                         1.25.1
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
nvidia-cufft-cu11             10.9.0.58
nvidia-curand-cu11            10.2.10.91
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusparse-cu11          11.7.4.91
nvidia-nccl-cu11              2.14.3
nvidia-nvtx-cu11              11.7.91
omegaconf                     2.3.0
opencv-python                 4.8.0.74
opencv-python-headless        4.5.5.64
opendatasets                  0.1.22
orjson                        3.9.2
packaging                     23.1
pandas                        2.0.3
parso                         0.8.3
pathy                         0.10.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.5.0
pip                           23.1.2
platformdirs                  3.9.1
plotly                        5.15.0
portalocker                   2.7.0
pre-commit                    3.3.3
preshed                       3.0.8
prompt-toolkit                3.0.39
protobuf                      4.23.4
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       12.0.1
pycocoevalcap                 1.2
pycocotools                   2.0.6
pydantic                      1.10.11
pydantic_core                 2.1.2
pydeck                        0.8.1b0
pydub                         0.25.1
Pygments                      2.15.1
Pympler                       1.0.1
pyparsing                     3.0.9
python-dateutil               2.8.2
python-magic                  0.4.27
python-multipart              0.0.6
python-qt-binding             0.4.4
python-slugify                8.0.1
pytz                          2023.3
pytz-deprecation-shim         0.1.0.post0
PyWavelets                    1.4.1
PyYAML                        6.0
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
referencing                   0.29.1
regex                         2023.6.3
requests                      2.31.0
resource_retriever            1.12.7
rich                          13.4.2
rosbag                        1.16.0
rosboost-cfg                  1.15.8
rosclean                      1.15.8
roscreate                     1.15.8
rosgraph                      1.16.0
roslaunch                     1.16.0
roslib                        1.15.8
roslint                       0.12.0
roslz4                        1.16.0
rosmake                       1.15.8
rosmaster                     1.16.0
rosmsg                        1.16.0
rosnode                       1.16.0
rosparam                      1.16.0
rospy                         1.16.0
rosservice                    1.16.0
rostest                       1.16.0
rostopic                      1.16.0
rosunit                       1.15.8
roswtf                        1.16.0
rpds-py                       0.8.10
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt_console                   0.4.11
rqt_dep                       0.4.12
rqt_graph                     0.4.14
rqt_gui                       0.5.3
rqt_gui_py                    0.5.3
rqt-image-view                0.4.17
rqt_launch                    0.4.9
rqt_logger_level              0.4.11
rqt-moveit                    0.5.10
rqt_msg                       0.4.10
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.11
rqt_publisher                 0.4.10
rqt_py_common                 0.5.3
rqt_py_console                0.4.10
rqt-reconfigure               0.5.5
rqt-robot-dashboard           0.5.8
rqt-robot-monitor             0.5.14
rqt_robot_steering            0.5.12
rqt_runtime_monitor           0.5.9
rqt-rviz                      0.7.0
rqt_service_caller            0.4.10
rqt_shell                     0.4.11
rqt_srv                       0.4.9
rqt_tf_tree                   0.6.3
rqt_top                       0.4.10
rqt_topic                     0.4.13
rqt_web                       0.4.10
rviz                          1.14.20
s3transfer                    0.6.1
safetensors                   0.3.1
salesforce-lavis              1.0.2
scikit-image                  0.21.0
scipy                         1.11.1
seaborn                       0.12.2
semantic-version              2.10.0
sensor-msgs                   1.13.1
sentencepiece                 0.1.99
setuptools                    68.0.0
six                           1.16.0
smach                         2.5.1
smach-ros                     2.5.1
smart-open                    6.3.0
smclib                        1.8.6
smmap                         5.0.0
sniffio                       1.3.0
spacy                         3.6.0
spacy-legacy                  3.0.12
spacy-loggers                 1.0.4
srdfdom                       0.6.3
srsly                         2.4.6
stack-data                    0.6.2
starlette                     0.27.0
streamlit                     1.24.1
SwissArmyTransformer          0.4.2
sympy                         1.12
tenacity                      8.2.2
tensorboardX                  2.6.1
text-unidecode                1.3
tf                            1.13.2
tf-conversions                1.13.2
tf2-geometry-msgs             0.7.6
tf2-kdl                       0.7.6
tf2-py                        0.7.6
tf2-ros                       0.7.6
thinc                         8.1.10
tifffile                      2023.7.10
timm                          0.4.12
tokenizers                    0.13.3
toml                          0.10.2
toolz                         0.12.0
topic-tools                   1.16.0
torch                         2.0.1
torchvision                   0.15.2
tornado                       6.3.2
tqdm                          4.65.0
trac_ik_python                1.6.6
traitlets                     5.9.0
transformers                  4.27.1
triton                        2.0.0
typer                         0.9.0
typing_extensions             4.7.1
tzdata                        2023.3
tzlocal                       4.3.1
uc-micro-py                   1.0.2
ultralytics                   8.0.120
urdfdom-py                    0.4.6
urllib3                       1.26.16
uvicorn                       0.22.0
validators                    0.20.0
virtualenv                    20.24.0
wasabi                        1.1.2
watchdog                      3.0.0
wcwidth                       0.2.6
webdataset                    0.2.48
webencodings                  0.5.1
websockets                    11.0.3
wheel                         0.40.0
xacro                         1.14.15
xxhash                        3.2.0
yarl                          1.9.2
zipp                          3.16.1

**Comment by Chen94yue** [comment]
> 

更新之后其他的东西需要更新吗？好像还是不对。用pip升级之后sat是0.4.3的版本，出来的结果还是差很远。用源码安装之后也不太对。

**Comment by 1049451037** [comment]
没有其他需要更新的，我本地是正常的，我也不太确定你的环境哪里出了问题

**Comment by Chen94yue** [comment]
好的，我试试

**Comment by Chen94yue** [comment]
问题解决了，pytorch降到1.13是正常的，建议更新requirements.txt

**Comment by 1049451037** [comment]
我们是支持torch2的，估计最近sat有什么更新导致的，正在排查修复

**Comment by 1049451037** [comment]
@Chen94yue 已修复，现在torch2应该也可以正常跑了，需要更新sat：

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install .
```

**Comment by lzw-lzw** [comment]
同样的问题，原来环境SwissArmyTransformer 0.4.3和torch 2.0.1，输入一张狗的图片，输出是“这是一张描绘着一对夫妇在一座小山丘上用餐的场景，画面中央是一个小木屋和一个小桌子，周围是一些植物和树木。桌子上有食物，包括米饭、蔬菜和一些水果，还有一些饮料或咖啡。这个场景充满了自然的美丽气息，让人感受到宁静和平和的氛围。
这张图片拍摄的位置可能位于一个美丽的自然环境中，例如森林、花园或者公园等地方。这种环境下的餐厅可以提供舒适和宁静的用餐体验，让人们能够享受大自然的美好和平静。”
更改SwissArmyTransformer到0.4.1后可以正常输出结果。
