### ISSUE TITLE
如何以合并后的模型为起点进行微调

### ISSUE THREAD

**Issue by threeColorFr** [THUDM/VisualGLM-6B#233]
我利用lora微调了一个模型，然后进行merge，然后想要以这个为起点进一步微调，我更换了Model_type为此模型的路径，结果报错：
`[2023-08-12 10:55:30,852] [INFO] [logging.py:96:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 1 optimizer
[2023-08-12 10:55:30,852] [INFO] [stage_1_and_2.py:133:__init__] Reduce bucket size 40000000
[2023-08-12 10:55:30,852] [INFO] [stage_1_and_2.py:134:__init__] Allgather bucket size 100000000
[2023-08-12 10:55:30,852] [INFO] [stage_1_and_2.py:135:__init__] CPU Offload: False
[2023-08-12 10:55:30,852] [INFO] [stage_1_and_2.py:136:__init__] Round robin gradient partitioning: False
Traceback (most recent call last):
  File "finetune_visualglm.py", line 196, in <module>
    training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=create_dataset_function, collate_fn=data_collator)
  File "/data/xiangwei/.miniconda3/envs/MMtransGPT/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 98, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/data/xiangwei/.miniconda3/envs/MMtransGPT/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 174, in setup_model_untrainable_params_and_optimizer
    model, optimizer, _, _ = deepspeed.initialize(
  File "/data/xiangwei/.miniconda3/envs/MMtransGPT/lib/python3.8/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/data/xiangwei/.miniconda3/envs/MMtransGPT/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 310, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/data/xiangwei/.miniconda3/envs/MMtransGPT/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1209, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/data/xiangwei/.miniconda3/envs/MMtransGPT/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1444, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/data/xiangwei/.miniconda3/envs/MMtransGPT/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 270, in __init__
    self.dtype = self.optimizer.param_groups[0]['params'][0].dtype
IndexError: list index out of range
ubuntu:89896:90062 [0] NCCL INFO [Service thread] Connection closed by localRank 0
ubuntu:89896:89896 [0] NCCL INFO comm 0x1fa20080 rank 0 nranks 1 cudaDev 0 busId 43000 - Abort COMPLETE
ubuntu:89896:90066 [0] NCCL INFO [Service thread] Connection closed by localRank 0
ubuntu:89896:89896 [0] NCCL INFO comm 0x88b18010 rank 0 nranks 1 cudaDev 0 busId 43000 - Abort COMPLETE`

**Comment by 1049451037** [comment]
这是因为你的训练参数为空，也就是没有可训练的参数

**Comment by threeColorFr** [comment]
这是为什么呢，因为我用的还是finetune_visualglm.sh的lora训练

**Comment by 1049451037** [comment]
https://github.com/THUDM/VisualGLM-6B/blob/main/finetune_visualglm.py#L34

因为merge以后就没有lora参数了，你可以根据你想训练什么参数修改这里
