### ISSUE TITLE
更新最新版后跑cli_demo.py文件报错

### ISSUE THREAD

**Issue by Derek-Kun** [THUDM/VisualGLM-6B#245]
我看issue里好多问题都是需要更新最新版sat和代码，sat更新到0.4.4以上就报错，0.3.7可以正常运行，但是用0.3.7的代码看issue里就会报其他问题错误，请问如何解决？

具体报错信息：
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
Traceback (most recent call last):
File "/code/dk/AIGC/Multimodal-GPT/VisualGLM-6B-2/VisualGLM-6B/cli_demo.py", line 103, in
main()
File "/code/dk/AIGC/Multimodal-GPT/VisualGLM-6B-2/VisualGLM-6B/cli_demo.py", line 30, in main
model, model_args = AutoModel.from_pretrained(
File "/opt/conda/envs/visual6b/lib/python3.8/site-packages/sat/model/base_model.py", line 310, in from_pretrained
return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
File "/opt/conda/envs/visual6b/lib/python3.8/site-packages/sat/model/base_model.py", line 302, in from_pretrained_base
model = get_model(args, model_cls, **kwargs)
File "/opt/conda/envs/visual6b/lib/python3.8/site-packages/sat/model/base_model.py", line 352, in get_model
model = model_cls(args, params_dtype=params_dtype, **kwargs)
File "/code/dk/AIGC/Multimodal-GPT/VisualGLM-6B-2/VisualGLM-6B/model/visualglm.py", line 32, in init
super().init(args, transformer=transformer, **kwargs)
File "/opt/conda/envs/visual6b/lib/python3.8/site-packages/sat/model/official/chatglm_model.py", line 175, in init
self.pad_token_id = args.pad_token_id
AttributeError: 'Namespace' object has no attribute 'pad_token_id'

**Comment by Derek-Kun** [comment]
File "/opt/conda/envs/visual6b/lib/python3.8/site-packages/sat/model/official/chatglm_model.py", line 175, in __init__
    self.pad_token_id = args.pad_token_id
AttributeError: 'Namespace' object has no attribute 'pad_token_id'
具体报错信息

**Comment by 1049451037** [comment]
说明你下载错了checkpoint文件，需要重新下载。

**Comment by Derek-Kun** [comment]
好的，多谢～

**Comment by 1049451037** [comment]
需要保证VisualGLM-6B的代码是新的，这样才能下载新的checkpoint文件。
