### ISSUE TITLE
使用python cli_demo.py --quant 4推理时报错，请问是什么原因

### ISSUE THREAD

**Issue by chaijunmaomao** [THUDM/VisualGLM-6B#281]
Traceback (most recent call last):
  File "cli_demo.py", line 103, in <module>
    main()
  File "cli_demo.py", line 36, in main
    device='cuda' if (torch.cuda.is_available() and args.quant is None) else 'cpu',
  File "/home1/qxgao/miniconda3/envs/py37/lib/python3.7/site-packages/sat/model/base_model.py", line 310, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home1/qxgao/miniconda3/envs/py37/lib/python3.7/site-packages/sat/model/base_model.py", line 304, in from_pretrained_base
    load_checkpoint(model, args, load_path=model_path, prefix=prefix)
  File "/home1/qxgao/miniconda3/envs/py37/lib/python3.7/site-packages/sat/training/model_io.py", line 222, in load_checkpoint
    sd = torch.load(checkpoint_name, map_location='cpu')
  File "/home1/qxgao/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home1/qxgao/miniconda3/envs/py37/lib/python3.7/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Gjh0000** [comment]
@chaijunmaomao 请问问题解决了吗？是什么原因？
