### ISSUE TITLE
demo_web

### ISSUE THREAD

**Issue by hzboomm** [THUDM/VisualGLM-6B#309]
运行demo_web.py报错：
Traceback (most recent call last):
  File "web_demo.py", line 129, in <module>
    main(args)
  File "web_demo.py", line 83, in main
    model, tokenizer = get_infer_setting(gpu_device=0, quant=args.quant)
  File "/data1/hzb/VisualGLM-6B/model/infer_util.py", line 21, in get_infer_setting
    model, args = VisualGLMModel.from_pretrained('visualglm-6b', args)
  File "/usr/local/lib/python3.8/dist-packages/sat/model/base_model.py", line 208, in from_pretrained
    model_path = auto_create(name, path=home_path, url=url)
  File "/usr/local/lib/python3.8/dist-packages/sat/resources/download.py", line 60, in auto_create
    raise e
  File "/usr/local/lib/python3.8/dist-packages/sat/resources/download.py", line 57, in auto_create
    download_with_progress_bar(file_path, url)
  File "/usr/local/lib/python3.8/dist-packages/sat/resources/download.py", line 29, in download_with_progress_bar
    response = requests.get(url, stream=True, headers=resume_header)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 695, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'r2://visualglm-6b.zip'
我好像无法下载这个权重

**Comment by 1049451037** [comment]
Please use the latest sat version. Your sat is outdated.

```
pip install -U SwissArmyTransformer
```

or

```
git clone https://github.com/THUDM/SwissArmyTransfomer
cd SwissArmyTransformer
pip install .
```

**Comment by hzboomm** [comment]
thanks！
