### ISSUE TITLE
微调时出现TypeError: string indices must be integers错误

### ISSUE THREAD

**Issue by 20191864218** [THUDM/VisualGLM-6B#314]
Traceback (most recent call last):
  File "/root/VisualGLM-6B/finetune_XrayGLM.py", line 194, in <module>
    training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=create_dataset_function, collate_fn=data_collator)
  File "/root/miniconda3/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 67, in training_main
    train_data, val_data, test_data = make_loaders(args, hooks['create_dataset_function'], collate_fn=collate_fn)
  File "/root/miniconda3/lib/python3.10/site-packages/sat/data_utils/configure_data.py", line 198, in make_loaders
    train = make_dataset(**data_set_args, args=args, dataset_weights=args.train_data_weights, is_train_data=True)
  File "/root/miniconda3/lib/python3.10/site-packages/sat/data_utils/configure_data.py", line 124, in make_dataset_full
    d = create_dataset_function(p, args)
  File "/root/VisualGLM-6B/finetune_XrayGLM.py", line 160, in create_dataset_function
    dataset = FewShotDataset(path, image_processor, tokenizer, args)
  File "/root/VisualGLM-6B/finetune_XrayGLM.py", line 117, in __init__
    image = processor(Image.open(item['img']).convert('RGB'))
TypeError: string indices must be integers
[2023-11-08 20:22:18,687] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 4613
[2023-11-08 20:22:18,687] [ERROR] [launch.py:321:sigkill_handler] ['/root/miniconda3/bin/python', '-u', 'finetune_XrayGLM.py', '--local_rank=0', '--experiment-name', 'finetune-XrayGLM', '--model-parallel-size', '1', '--mode', 'finetune', '--train-iters', '300', '--resume-dataloader', '--max_source_length', '64', '--max_target_length', '256', '--lora_rank', '10', '--pre_seq_len', '4', '--train-data', '/root/autodl-tmp/Xray/openi-zh.json', '--valid-data', '/root/autodl-tmp/Xray/openi-zh.json', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--save-interval', '300', '--eval-interval', '10000', '--save', './checkpoints', '--split', '1', '--eval-iters', '10', '--eval-batch-size', '8', '--zero-stage', '1', '--lr', '0.0001', '--batch-size', '8', '--skip-init', '--fp16', '--use_lora'] exits with return code = 1

**Comment by DongnuanCai** [comment]
Has the issue been resolved?

**Comment by GG6Bond** [comment]
请问怎么解决的？

**Comment by xlsssss** [comment]
和visual_GLM 的dataset.json对比可知，openi-zh.json 还不是最终的可训练的 json版本。执行./data/build_ch_prompt.py，把finetune_XrayGLM.sh 里面的 json路径改成刚刚生成的路径。
