### ISSUE TITLE
AttributeError: 'FakeTokenizer' object has no attribute 'encode'

### ISSUE THREAD

**Issue by WangZY1111** [THUDM/VisualGLM-6B#335]
Traceback (most recent call last):
  File "finetune_visualglm.py", line 194, in <module>
    training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=create_dataset_function, collate_fn=data_collator)
  File "/home/wangzy/anaconda3/envs/LVM/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 67, in training_main
    train_data, val_data, test_data = make_loaders(args, hooks['create_dataset_function'], collate_fn=collate_fn)
  File "/home/wangzy/anaconda3/envs/LVM/lib/python3.8/site-packages/sat/data_utils/configure_data.py", line 200, in make_loaders
    train = make_dataset(**data_set_args, args=args, dataset_weights=args.train_data_weights, is_train_data=True)
  File "/home/wangzy/anaconda3/envs/LVM/lib/python3.8/site-packages/sat/data_utils/configure_data.py", line 126, in make_dataset_full
    d = create_dataset_function(p, args)
  File "finetune_visualglm.py", line 160, in create_dataset_function
    dataset = FewShotDataset(path, image_processor, tokenizer, args)
  File "finetune_visualglm.py", line 118, in __init__
    input0 = tokenizer.encode("<img>", add_special_tokens=False)
AttributeError: 'FakeTokenizer' object has no attribute 'encode'

how can I solve it

**Comment by Tom98714** [comment]
你好，这个问题解决了吗，我也遇到这个问题了

**Comment by xiongxiaochu** [comment]
遇到这个问题+1，请问解决了吗？

**Comment by Tom98714** [comment]
找到了问题。还没有彻底解决




eternal&nbsp;？_frank_test
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THUDM/VisualGLM-6B"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 下午4:21
***@***.***&gt;;
抄送:&nbsp;"Future ***@***.******@***.***&gt;;
主题:&nbsp;Re: [THUDM/VisualGLM-6B] AttributeError: 'FakeTokenizer' object has no attribute 'encode' (Issue #335)





 
遇到这个问题+1，请问解决了吗？

**Comment by Tom98714** [comment]
> 遇到这个问题+1，请问解决了吗？

请检查所有的模型路径和分词器路径是否为本地路径，默认是THUDM/Visualglm-6b，如果本地运行的话，需要把路径修改到本地的相应位置，如果能直接访问到huggingface，应该不会发生这个问题

**Comment by xiongxiaochu** [comment]
> > 遇到这个问题+1，请问解决了吗？
> 
> 请检查所有的模型路径和分词器路径是否为本地路径，默认是THUDM/Visualglm-6b，如果本地运行的话，需要把路径修改到本地的相应位置，如果能直接访问到huggingface，应该不会发生这个问题

都修改成了本地路径，我们这边机器无法访问huggingface

**Comment by Tom98714** [comment]
> > > 遇到这个问题+1，请问解决了吗？
> > 
> > 
> > 请检查所有的模型路径和分词器路径是否为本地路径，默认是THUDM/Visualglm-6b，如果本地运行的话，需要把路径修改到本地的相应位置，如果能直接访问到huggingface，应该不会发生这个问题
> 
> 都修改成了本地路径，我们这边机器无法访问huggingface

你需要提前把所需要的模型，和分词器都下载到本地，然后在把路径修改到相应路径
这里是sat模型下载链接
https://www.wisemodel.cn/models/ZhipuAI/VisualGLM-6B-SAT/file

**Comment by Tom98714** [comment]
> > > 遇到这个问题+1，请问解决了吗？
> > 
> > 
> > 请检查所有的模型路径和分词器路径是否为本地路径，默认是THUDM/Visualglm-6b，如果本地运行的话，需要把路径修改到本地的相应位置，如果能直接访问到huggingface，应该不会发生这个问题
> 
> visual-glm修改成了本地路径，chatglm那个没看到修改的位置

这里是huggingface的镜像网站，请仔细阅读
https://hf-mirror.com/

**Comment by xiongxiaochu** [comment]
> > > > 遇到这个问题+1，请问解决了吗？
> > > 
> > > 
> > > 请检查所有的模型路径和分词器路径是否为本地路径，默认是THUDM/Visualglm-6b，如果本地运行的话，需要把路径修改到本地的相应位置，如果能直接访问到huggingface，应该不会发生这个问题
> > 
> > 
> > 都修改成了本地路径，我们这边机器无法访问huggingface
> 
> 你需要提前把所需要的模型，和分词器都下载到本地，然后在把路径修改到相应路径 这里是sat模型下载链接 https://www.wisemodel.cn/models/ZhipuAI/VisualGLM-6B-SAT/file

<img width="371" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/3940432/5db2990d-c9ee-4958-a7dc-3f4440708832">
通过cli-demo下载了，长这样是对的吗？

**Comment by Tom98714** [comment]
> > > > > 遇到这个问题+1，请问解决了吗？
> > > > 
> > > > 
> > > > 请检查所有的模型路径和分词器路径是否为本地路径，默认是THUDM/Visualglm-6b，如果本地运行的话，需要把路径修改到本地的相应位置，如果能直接访问到huggingface，应该不会发生这个问题
> > > 
> > > 
> > > 都修改成了本地路径，我们这边机器无法访问huggingface
> > 
> > 
> > 你需要提前把所需要的模型，和分词器都下载到本地，然后在把路径修改到相应路径 这里是sat模型下载链接 https://www.wisemodel.cn/models/ZhipuAI/VisualGLM-6B-SAT/file
> 
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/3940432/300733586-5db2990d-c9ee-4958-a7dc-3f4440708832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDQwMzcsIm5iZiI6MTcwNjYwMzczNywicGF0aCI6Ii8zOTQwNDMyLzMwMDczMzU4Ni01ZGIyOTkwZC1jOWVlLTQ5NTgtYTdkYy0zZjQ0NDA3MDg4MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMDgzNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdjODI0NDJkMWZiNzljZmM4MTY3MjgwMTkyZDQzNTE3ZDMwNTgwMWU2OTUyNzVkNjk5MDYxMWRjOGMxNWY4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dfnG1OZ5i-DPLa-aOW1F2tjfgF0GadXvzwl30NpN1E8"> 通过cli-demo下载了，长这样是对的吗？

是的

**Comment by xiongxiaochu** [comment]
> https://hf-mirror.com/

那分词器是也需要放在visualglm-6b文件夹下吗？

**Comment by Tom98714** [comment]
> > https://hf-mirror.com/
> 
> 那分词器是也需要放在visualglm-6b文件夹下吗？

是的，全都需要，都需要提前准备好，并修改相应配置文件、代码中的路径

**Comment by xiongxiaochu** [comment]
> > > https://hf-mirror.com/
> > 
> > 
> > 那分词器是也需要放在visualglm-6b文件夹下吗？
> 
> 是的，全都需要，都需要提前准备好，并修改相应配置文件、代码中的路径

收到，把model_config.json里的tokenizer_type改成本地chatglm的路径就可以了~

**Comment by mcocean2000** [comment]
chatglm也要下载到本地吗

**Comment by mcocean2000** [comment]
> > > > https://hf-mirror.com/
> > > 
> > > 
> > > 那分词器是也需要放在visualglm-6b文件夹下吗？
> > 
> > 
> > 是的，全都需要，都需要提前准备好，并修改相应配置文件、代码中的路径
> 
> 收到，把model_config.json里的tokenizer_type改成本地chatglm的路径就可以了~

chatglm也要下载到本地吗？

**Comment by BUZZ0328** [comment]
> > > > https://hf-mirror.com/
> > > 
> > > 
> > > 那分词器是也需要放在visualglm-6b文件夹下吗？
> > 
> > 
> > 是的，全都需要，都需要提前准备好，并修改相应配置文件、代码中的路径
> 
> 收到，把model_config.json里的tokenizer_type改成本地chatglm的路径就可以了~

<img width="641" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/109131708/194e4657-dce0-466f-925b-730fc0f67cb5">
 #请问下载的模型和分词器是放在如图上放置吗，还缺什么文件吗，model_config.json里的tokenizer_type这里修改为/home/root1/data/glm/VisualGLM-6B/THUDM/visualglm-6b（这是我图上的路径），tokenizer_config.json里的name_or_path也一样修改对吗？
