### ISSUE TITLE
使用CPU加载模型推理时出现如下报错

### ISSUE THREAD

**Issue by JiaXinSugar-114514** [THUDM/VisualGLM-6B#34]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\chatglm\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\chatglm\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\chatglm\lib\site-packages\gradio\blocks.py", line 1039, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\chatglm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\chatglm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\chatglm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\chatglm\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "D:\Code\VisualGLM-6B-main\web_demo_hf.py", line 56, in predict
    chatbot.append((parse_text(input), ""))
AttributeError: 'NoneType' object has no attribute 'append'求大神解决，感觉CPU部署还是有问题

**Comment by coolPornotcoolP** [comment]
gpu部署同样遇到了这个问题

**Comment by ZieeoHaa** [comment]
在VisualGLM-6B/web_demo_hf.py中，line55
if image_path is None:
     return [(input, "图片不能为空。请重新上传图片并重试。")], []

改成
if image_path is None:
     image_path = ""

**Comment by sonicno1** [comment]
torch安装的也是cpu版本,使用CPU时报错：
  File "/usr/local/python3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
