### ISSUE TITLE
python web_demo.py报错

### ISSUE THREAD

**Issue by Dreamior** [THUDM/VisualGLM-6B#352]
(visualglm) bit@ubuntu:~/LLM/VisualGLM-6B$ python web_demo.py --quant 4
Traceback (most recent call last):
  File "/home/bit/LLM/VisualGLM-6B/web_demo.py", line 3, in <module>
    import gradio as gr
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/gradio/processing_utils.py", line 30, in <module>
    async_client = httpx.AsyncClient()
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/httpx/_client.py", line 1429, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/httpx/_client.py", line 217, in _get_proxy_map
    return {
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/httpx/_client.py", line 218, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/bit/anaconda3/envs/visualglm/lib/python3.10/site-packages/httpx/_config.py", line 336, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7890/')

**Comment by LFWOvO** [comment]
You need to shut down all the proxy and start a new terminal to run the command
