### ISSUE TITLE
utoModel.from_pretrained("../visualglm-6b", trust_remote_code=True).half().cuda()  error

### ISSUE THREAD

**Issue by wavelet2008** [THUDM/VisualGLM-6B#74]
(face19) lan@lan:~/sdf/VisualGLM-6B$ python  cli_demo_hf.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/home/lan/sdf/VisualGLM-6B/cli_demo_hf.py", line 7, in <module>
    tokenizer = AutoTokenizer.from_pretrained("../visualglm-6b", trust_remote_code=True)
  File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 679, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1958, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 221, in __init__
    self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens)
  File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 64, in __init__
    self.text_tokenizer = TextTokenizer(vocab_file)
  File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 22, in __init__
    self.sp.Load(model_path)
  File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by AdJIa** [comment]
> (face19) lan@lan:~/sdf/VisualGLM-6B$ python cli_demo_hf.py Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision. Traceback (most recent call last): File "/home/lan/sdf/VisualGLM-6B/cli_demo_hf.py", line 7, in tokenizer = AutoTokenizer.from_pretrained("../visualglm-6b", trust_remote_code=True) File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 679, in from_pretrained return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained return cls._from_pretrained( File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1958, in _from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 221, in **init** self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens) File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 64, in **init** self.text_tokenizer = TextTokenizer(vocab_file) File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 22, in **init** self.sp.Load(model_path) File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/sentencepiece/**init**.py", line 905, in Load return self.LoadFromFile(model_file) File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/sentencepiece/**init**.py", line 310, in LoadFromFile return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

@wavelet2008 有解决吗 我也遇到同样的问题

**Comment by shunyuchu** [comment]
参考一下这个：https://github.com/THUDM/ChatGLM-6B/issues/770

**Comment by shunyuchu** [comment]
> > (face19) lan@lan:~/sdf/VisualGLM-6B$ python cli_demo_hf.py Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision. Traceback (most recent call last): File "/home/lan/sdf/VisualGLM-6B/cli_demo_hf.py", line 7, in tokenizer = AutoTokenizer.from_pretrained("../visualglm-6b", trust_remote_code=True) File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 679, in from_pretrained return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained return cls._from_pretrained( File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1958, in _from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 221, in **init** self.sp_tokenizer = SPTokenizer(vocab_file, num_image_tokens=num_image_tokens) File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 64, in **init** self.text_tokenizer = TextTokenizer(vocab_file) File "/home/lan/.cache/huggingface/modules/transformers_modules/visualglm-6b/tokenization_chatglm.py", line 22, in **init** self.sp.Load(model_path) File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/sentencepiece/**init**.py", line 905, in Load return self.LoadFromFile(model_file) File "/home/lan/anaconda3/envs/face19/lib/python3.9/site-packages/sentencepiece/**init**.py", line 310, in LoadFromFile return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
> 
> @wavelet2008 有解决吗 我也遇到同样的问题

参考一下这个：https://github.com/THUDM/ChatGLM-6B/issues/770

**Comment by Jerryyuanyuan** [comment]
有visualGLM模型的清华云盘的ice_text.model么？
