### ISSUE TITLE
centos 环境 使用pip安装依赖报错

### ISSUE THREAD

**Issue by shihzenq** [THUDM/VisualGLM-6B#88]
1、pip install -i https://pypi.org/simple -r requirements.txt
2、pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt
两个命令尝试过，都报如下错误：
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting SwissArmyTransformer>=0.3.6 (from -r requirements.txt (line 1))
  Using cached https://mirrors.aliyun.com/pypi/packages/35/72/33d121b3a54fa1bb42fb3f5796e47be650dfe9247b83aba09a0cefafc378/SwissArmyTransformer-0.3.6-py3-none-any.whl (2.4 MB)
Requirement already satisfied: torch>1.10.0 in /home/tushen/anaconda3/envs/python39/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.0.0)
Collecting torchvision (from -r requirements.txt (line 3))
  Downloading https://mirrors.aliyun.com/pypi/packages/41/9e/8809e45a084680394e8d219fcf8a2c0eed2dddf1ec0a7968f4052826a6e9/torchvision-0.15.2-cp39-cp39-manylinux1_x86_64.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 280.2 kB/s eta 0:00:00
Requirement already satisfied: transformers>=4.27.1 in /home/tushen/anaconda3/envs/python39/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (4.27.1)
Requirement already satisfied: mdtex2html in /home/tushen/anaconda3/envs/python39/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (1.2.0)
Requirement already satisfied: gradio in /home/tushen/anaconda3/envs/python39/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (3.28.0)
Collecting deepspeed (from SwissArmyTransformer>=0.3.6->-r requirements.txt (line 1))
  Using cached https://mirrors.aliyun.com/pypi/packages/9e/6a/ce4e9afcf36f242f55bf2c91fa1366b26f0f40653d98a96c0f64b7154c12/deepspeed-0.9.2.tar.gz (779 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2kfzckpb/deepspeed_c3e7c332f93d4376aa90c71fd1a48d84/setup.py", line 81, in <module>
          cuda_major_ver, cuda_minor_ver = installed_cuda_version()
        File "/tmp/pip-install-2kfzckpb/deepspeed_c3e7c332f93d4376aa90c71fd1a48d84/op_builder/builder.py", line 41, in installed_cuda_version
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Sleepychord** [comment]
你需要先安装cuda，可以搜一下conda 安装cudatoolkit的方法。

**Comment by shihzenq** [comment]
现在安装可以了。谢谢您
