### ISSUE TITLE
linux 启动 cli_demo.py 报错No such file or directory: 'visualglm-6b/model_config.json'

### ISSUE THREAD

**Issue by shihzenq** [THUDM/VisualGLM-6B#93]
启动cli_demo.py之后报：
Traceback (most recent call last):
  File "/data/VisualGLM-6B/cli_demo.py", line 103, in <module>
    main()
  File "/data/VisualGLM-6B/cli_demo.py", line 30, in main
    model, model_args = AutoModel.from_pretrained(
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/sat/model/base_model.py", line 271, in from_pretrained
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/opt/miniconda3/envs/py39/lib/python3.9/site-packages/sat/arguments.py", line 423, in update_args_with_file
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'visualglm-6b/model_config.json'

我在huggingface 上下载的文件里面没有model_config.json。
目录下只有这些。
<img width="1156" alt="image" src="https://github.com/THUDM/VisualGLM-6B/assets/35477865/88a1a097-32c4-469b-9471-1c93431c260c">

请问如何解决

**Comment by 1049451037** [comment]
从huggingface下载的checkpoint需要用cli_demo_hf.py启动

**Comment by shihzenq** [comment]
好的，谢谢您。

**Comment by shihzenq** [comment]
@1049451037 您好，那什么时候需要用cli_demo.py 启动。只有在微调后才能用cli_demo.py吗？

**Comment by 1049451037** [comment]
用cli_demo.py启动需要从清华云盘下载sat的checkpoint

**Comment by shihzenq** [comment]
@1049451037 您好，huggingface的checkpoint 和 清华云盘 sat的checkpoint 区别是什么，哪个更优

**Comment by 1049451037** [comment]
两个checkpoint是一样的参数，只是格式不一样

**Comment by shihzenq** [comment]
好的，谢谢您

**Comment by buzhihuoyefeng** [comment]
我用两个启动命令都是提示没有这个文件啊
